# Generated by Django 6.0.4 on 2026-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('future', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Filial', 'verbose_name_plural': 'Filiallar'},
        ),
        migrations.AlterModelOptions(
            name='queue',
            options={'ordering': ['number'], 'verbose_name': 'Navbat', 'verbose_name_plural': 'Navbatlar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Xizmat', 'verbose_name_plural': 'Xizmatlar'},
        ),
        migrations.AlterUniqueTogether(
            name='queue',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('waiting', 'Kutilmoqda'), ('active', 'Jarayonda'), ('done', 'Tugallangan'), ('cancelled', 'Bekor qilingan')], default='waiting', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='queue',
            constraint=models.UniqueConstraint(fields=('service', 'branch', 'number'), name='unique_queue_number'),
        ),
    ]
